### PR TITLE
WIP: Bedrock server

### LINKED ISSUE #20: kann ich bitte auch einen bedrock server haben?
Ich würde gerne mit dem iPad und Freunden spielen, dazu brauche ich einen bedrock server.

### PR DESCRIPTION
**Pull request by goern**
closes #20

### CODE REVIEW

**Comment by goern** [comment]
@tumido @durandom looks like OCP doesnt like to use the Bedrock port, any idea how to fix it?
`The Service "minecraft-server-creative" is invalid: spec.ports[0].nodePort: Invalid value: 19132: provided port is not in the valid range. The range of valid ports is 30000-32767`

**Comment by durandom** [comment]
https://github.com/itzg/docker-minecraft-bedrock-server/issues/6

Can you configure the port in the config file?
After it's being created. Which might be a chicken egg problem

Christoph Görn ***@***.***> schrieb am So. 2. Mai 2021 um
08:37:

**Comment by goern** [comment]
uhh.. I was under the impression that the bedrock client needs this specific port, let's test with ....

**Comment by tumido** [comment]
@goern the node port range is fixed and I don't think we can do much about it. The range is controlled via `apiserver` configuration, so if we want to change this range, we would need to reconfigure the cluster...

https://docs.openshift.com/container-platform/4.7/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-nodeport.html#nw-using-nodeport_configuring-ingress-cluster-traffic-nodeport

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/networking/configuring-node-port-service-range

**Comment by tumido** [comment]
Like.. in the end it's patching a single config resource, but it supports only a single range definition + may cause firewall troubles... :shrug:

**Pull request closed without merging**
